apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fastfood
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9mYXN0Zm9vZF9wYWdhbWVudG9zX3VzZXI6ZmFzdGZvb2RfcGFnYW1lbnRvc19wYXNzd29yZEBmYXN0Zm9vZC1wYWdhbWVudG9zLmpxaWVpcncubW9uZ29kYi5uZXQvZmFzdGZvb2QtcGFnYW1lbnRvcz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1mYXN0Zm9vZC1wYWdhbWVudG9zYW1lbnRvcyZ0bHM9dHJ1ZQ==

