version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_dev_network_pagamentos
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_pagamentos:/var/lib/postgresql/data
    networks:
      - postgres_dev_network
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-sqs
    ports:
      - "4566:4566" # porta principal de acesso
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/var/lib/localstack"

volumes:
  postgres_data_pagamentos:
  localstack_data:

networks:
  postgres_dev_network: